apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: efs-static
  resources:
    requests:
      storage: 5Gi