apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: expense
spec:
  # One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx # This will fetch official nginx image from docker hub
