apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23" # This is just for example
    imageregistry: "https://hub.docker.com"
spec:
  containers:
  - name: nginx
    image: nginx