apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: trainee
      value: Pradeep
    - name: duration
      value: 120Hrs
    - name: course
      value: Devops
