apiVersion: v1
kind: Pod
metadata: 
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # Soft Limit
      requests:
        memory: "70mi" # mi is mebibytes 1Mi = 1.048 Mb
        cpu: "100m" # m is millicore. so 100m is 0.1 core or 10% of 1 core
    # Hard Limit
      limits:
        memory: "100mi"
        cpu: "100m"
