apiVersion: v1 
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector: # Labels are used as selectors here, this service will be attached to the pod whose labels matches the selectors
    project: expense
    environment: dev
    component: backend
    version: 1.0.0
    demo: np
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # - target container port. So traffic comes from port 80 of service to port 80 of pod. P capital in targetPort
    nodePort: 30007
--- 
apiVersion: v1 
kind: Pod
metadata:
  name: backend-np
  labels:
    project: expense
    environment: dev
    component: backend
    version: 1.0.0
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx