apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # These are Replicaset Labels
  labels:
    app: frontend
    tier: web
spec:
  replicas: 3
  selector:
  # Replica set use these labels to find which pod they belongs to and manage them. Also create a pod using template if already not present
    matchLabels:
      app: frontend
      tier: web
# Pod is a subset of ReplicaSet. The below is the Pod definition. or the template for pod creation
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl

    # Explanation of Core Sections:
# - apiVersion: Specifies the Kubernetes API version.
# - kind: Defines the resource type (Deployment).
# - metadata: Provides identifying details like name, namespace, and labels.
# - spec: Defines deployment details like replicas and selectors.
# - template: Describes the structure of pods to be created.
# - containers: Lists containers, specifying the image and ports.