apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # Labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: pradeepgorle/deployment:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # Labels are used as selectors here, this service will be attached to the pod whose labels matches the selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 # - target container port. So traffic comes from port 80 of service to port 80 of pod. P capital in targetPort
    nodePort: 30007 # This opens the fixed port 30007 on the node (server), you can make the changes in security group



