apiVersion: v1 
kind: Service
metadata: 
  name: nginx-headless
  labels:
    app: nginx
    demo: statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: none # should be none for headless service
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
      demo: statefulset # has to match spec.template.metadata.labels
  serviceName: "nginx-headless" # name of the headless service
  replicas: 3 # default is 1
  minReadySeconds: 10 # 0 by default
  template:
    metadata:
      labels:
        app: nginx
        demo: statefulset # has to match spec.selector.matchLabels.
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
    # Instead of creating a  PVC resource, you can you can directly provide the PVC here in statefulset template itself like below.
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

        
