apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
  namespace: expense
spec:
  # One POD can contain multiple containers
  serviceAccount: expense-mysql-secret
  initContainers:
  - name: awscli
    image: amazon/aws-cli
    command: ['sh','-c', "aws secretmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text > /secrets/.env"]
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  containers:
  - name: nginx
    image: nginx # This will fetch official nginx image from docker hub
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
    volumes:
    - name: secret-volume
      emptyDir: {} # you can mention the size if you require